# Sales Records Analysis
### Author: Jonathan Lopez
### Exercise 2.E Using functions for analyzing data
This notebook analyzes a small sales dataset using Python functions.
Each function takes the full dataset as its first argument.

In [1]:
sales_data = [
    ('Laptop',   'East',  1200.00),
    ('Phone',    'West',   850.00),
    ('Tablet',   'East',   400.00),
    ('Monitor',  'South',  650.00),
    ('Keyboard', 'West',    75.00),
    ('Laptop',   'South', 1150.00),
    ('Phone',    'East',   900.00),
    ('Tablet',   'West',   425.00),
    ('Monitor',  'East',   680.00),
    ('Keyboard', 'South',   80.00),
    ('Laptop',   'West',  1300.00),
    ('Phone',    'West',   820.00),
]

## Lab 1. Total sales by region

In [2]:
# region_total()
def region_total(data, region):
    return sum(amt for _, r, amt in data if r == region)

In [3]:
# Test it
print(region_total(sales_data, 'East'))
print(region_total(sales_data, 'West'))
print(region_total(sales_data, 'South'))

3180.0
3470.0
1880.0


## Lab 2. Count of sales by region

In [4]:
# region count
def region_count(data, region):
    return sum(1 for _, r, _ in data if r == region)

In [5]:
# test
print(region_count(sales_data, 'East'))
print(region_count(sales_data, 'West'))
print(region_count(sales_data, 'South'))

4
5
3


## Lab 3. Average sale amount by region

In [6]:
# region average
def region_average(data, region):
    count = region_count(data, region)
    if count == 0:
        return 0
    return region_total(data, region) / count    

In [7]:
# test
print(region_average(sales_data, 'East'))
print(region_average(sales_data, 'West'))
print(region_average(sales_data, 'South'))
print(region_average(sales_data, 'North'))

795.0
694.0
626.6666666666666
0


## Lab 4. Filter by sale amount

In [8]:
# sales above and below
def sales_above(data, threshold):
    return [record for record in data if record[2] > threshold]

def sales_below(data, threshold):
    return [record for record in data if record[2] < threshold]

In [9]:
# Test
below_500 = sales_below(sales_data, 500)
for record in below_500:
    print(record)

('Tablet', 'East', 400.0)
('Keyboard', 'West', 75.0)
('Tablet', 'West', 425.0)
('Keyboard', 'South', 80.0)


## Lab 5. Top and bottom sale

In [10]:
def top_sale(data):
    return max(data, key=lambda s: s[2])

def bottom_sale(data):
    return min(data, key=lambda s: s[2])

In [12]:
print(top_sale(sales_data))
print(bottom_sale(sales_data))

('Laptop', 'West', 1300.0)
('Keyboard', 'West', 75.0)


The top sale was a **Laptop** in the **West** region for **$1,300.00**.

The bottom sale was a **Keyboard** in the **West** region for **$75.00**

## Lab 6. Apply a discount

In [13]:
# apply discount
def apply_discount(data, discount_pct):
    return list(map(lambda s: (s[0], s[1], s[2] * (1 - discount_pct)), data))

In [14]:
# test
discounted = apply_discount(sales_data, 0.15)

print("Before discount:")
for record in sales_data[:3]:
    print(record)

print("\nAfter 15% discount:")
for record in discounted[:3]:
    print(record)

Before discount:
('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Tablet', 'East', 400.0)

After 15% discount:
('Laptop', 'East', 1020.0)
('Phone', 'West', 722.5)
('Tablet', 'East', 340.0)


## Lab 7. Unique regions

In [15]:
# unique regions
def unique_regions(data):
    return sorted(set(r for _, r, _ in data))

print(unique_regions(sales_data))

['East', 'South', 'West']


'unique_regions()' is useful because it dynamically discovers what regions exist in the dataset without hardcoding them. This means the code still works correctly if new regions are added later. You could use this same pattern to find unique products, departments, categories, or any other grouping field in a dataset.

## Lab 8. Region summary

In [18]:
# region summary
def region_summary(data, region):
    region_data = [record for record in data if record[1] == region]
    total = region_total(data, region)
    count = region_count(data, region)
    average = region_average(data, region)
    top = top_sale(region_data)

    print(f"=== {region} Region ===")
    print(f"Records: {count}")
    print(f"Total Sales: ${total:,.2f}")
    print(f"Average Sale: ${average:,.2f}")
    print(f"Top Sale: {top[0]} - ${top[2]:,.2f}")
    print()

In [19]:
# test
region_summary(sales_data, 'East')
region_summary(sales_data, 'West')
region_summary(sales_data, 'South')

=== East Region ===
Records: 4
Total Sales: $3,180.00
Average Sale: $795.00
Top Sale: Laptop - $1,200.00

=== West Region ===
Records: 5
Total Sales: $3,470.00
Average Sale: $694.00
Top Sale: Laptop - $1,300.00

=== South Region ===
Records: 3
Total Sales: $1,880.00
Average Sale: $626.67
Top Sale: Laptop - $1,150.00



## Lab 9. Full summary

In [20]:
# Loop through the regions
for region in unique_regions(sales_data):
    region_summary(sales_data, region)

=== East Region ===
Records: 4
Total Sales: $3,180.00
Average Sale: $795.00
Top Sale: Laptop - $1,200.00

=== South Region ===
Records: 3
Total Sales: $1,880.00
Average Sale: $626.67
Top Sale: Laptop - $1,150.00

=== West Region ===
Records: 5
Total Sales: $3,470.00
Average Sale: $694.00
Top Sale: Laptop - $1,300.00



## Summary
In these labs, I learned how to:
- Break analysis into small reusable functions
- Use generator expressions to filter and sum data efficiently
- Reuse functions inside other functions to avoid repeating logic
- Use 'map()' and 'lambda' to transform datasets
- Use 'max()' and 'min()' with a key to find records by a specific field
- Dynamically loop over unique values instead of hardcoding region names